# Imagen base ligera de Python
FROM python:3.11-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia solo requirements.txt para usar cache y no reinstalar todo cada vez
COPY requirements.txt .

# Instala dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia todo el código de la app
COPY . .

# Exponer puerto 8000 para FastAPI
EXPOSE 8000

# Comando para correr FastAPI en modo desarrollo
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
